# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 840bb3a72f348ac2f8ff38e0b12ef4fda9c9f97046ba0323b03c6f626813725c63b77f2c5153215321d78301a92cf00c6c327ffbb590df0f5d56147d3b7af70d

test:
  secret_key_base: ce6b18816104c4ece26d9837691f0f8475fe6107facc900733342043b4d0ad2f067b3bc7e81c0e1223d21bd627ea9811077997d20fdc2f0078d6e1713f86d67d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
